// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/retreats/routes/admin/(dashboard)/revenue/events/[id]/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import type { ComponentProps } from "react";
import Body from "@/entities/retreats/routes/admin/(dashboard)/revenue/events/[id]/page";
import { TripCostPanel } from "@/app/shell";

export default function Page(props: Omit<ComponentProps<typeof Body>, "tripCostPanel">) {
  return <Body {...props} tripCostPanel={TripCostPanel} />;
}

export const dynamic = "force-dynamic";
