import { summarizeResult } from "./routine-runs";
import { runByHand } from "./run-by-hand";

// Run now for every scheduled routine (Y.25). A routine's work is its cron
// handler, the GET its entity exports from crons/<name>.ts, wrapped in
// withRoutineRun and mounted at app/api/cron/<name>/route.ts. Settings ->
// Agents runs that same GET, through the mount, in-process, so a
// run by hand goes through the routine's own claim, its own effect keys and
// its own outcome rule, exactly as the schedule's run does.
//
// It never calls the site's own URL: a request from a function to its own
// deployment is what Vercel answered 508 (loop detected) for the letter's call
// to action page (Y.75), and it would need the cron secret besides.
//
// The kernel may import neither app/ nor an entity, so it holds the handlers
// as the composition root hands them over: app/routines.ts, generated by
// scripts/gen-deployment.mjs from the cron mounts of the installed entities,
// registers one loader per scheduled routine at boot, from instrumentation.ts.
// The loaders import lazily, so booting does not load every cron's graph.
//
// Keyed on globalThis with Symbol.for, because Next gives instrumentation,
// routes and actions their own copy of each module (W.170): registered at
// boot in one copy, read by the server action in another.

export type RoutineEntryPoint = (req: Request) => Promise<Response>;
export type RoutineEntryPoints = Readonly<Record<string, () => Promise<RoutineEntryPoint>>>;

const KEY = Symbol.for("edge8.audit.routine-entry-points");
type Store = { points: RoutineEntryPoints | null };

function store(): Store {
  const g = globalThis as unknown as Record<symbol, Store | undefined>;
  return (g[KEY] ??= { points: null });
}

/** Called by app/routines.ts at boot. Idempotent: a later call replaces the set. */
export function registerRoutineEntryPoints(points: RoutineEntryPoints): void {
  store().points = points;
}

/** Whether the composition root registered a handler for this routine. */
export function hasRoutineEntryPoint(routineId: string): boolean {
  return Boolean(store().points?.[routineId]);
}

export type ByHandRun =
  | { ok: true; status: "ok" | "skipped" | "error"; summary: string | null }
  | { ok: false; error: string };

// The status a cron body reports, read the way recordRoutineRun judges it
// closely enough to tell the person what happened: an explicit skipped, an
// error field or a non-2xx, or ok.
function statusOf(res: Response, body: Record<string, unknown> | null): "ok" | "skipped" | "error" {
  if (!res.ok || typeof body?.error === "string") return "error";
  return body?.status === "skipped" ? "skipped" : "ok";
}

/**
 * Run one scheduled routine now, in this process, as `actor`. The handler's
 * own withRoutineRun opens and closes the routine_runs row, so the run lands
 * in the history like any other, with a fresh tick. What comes back is what
 * the run said, for the button; the row is the record.
 */
export async function runRoutineByHand(routineId: string, actor: string): Promise<ByHandRun> {
  const points = store().points;
  if (!points) return { ok: false, error: "The routine handlers were never registered (app/routines.ts, from instrumentation.ts)." };
  const load = points[routineId];
  if (!load) return { ok: false, error: `${routineId} has no handler this button can run.` };

  // The path is the routine id, as the schedule calls it. The origin is never
  // dialled: a handler reads the URL only for its path and query.
  const req = new Request(new URL(routineId, "http://run-now.invalid"), { method: "GET" });
  let res: Response;
  try {
    const handler = await load();
    res = await runByHand({ actor }, () => handler(req));
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  let body: Record<string, unknown> | null = null;
  try {
    const parsed: unknown = await res.json();
    body = parsed && typeof parsed === "object" ? (parsed as Record<string, unknown>) : null;
  } catch {
    body = null;
  }
  const status = statusOf(res, body);
  const reason = typeof body?.reason === "string" ? body.reason : null;
  const summary = status === "error" ? (typeof body?.error === "string" ? body.error : `HTTP ${res.status}`) : (reason ?? summarizeResult(body));
  return { ok: true, status, summary };
}
