// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/team/routes/team/(dashboard)/profile/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import type { ComponentProps } from "react";
import Body from "@/entities/team/routes/team/(dashboard)/profile/page";
import { ProfileClaimsPanel } from "@/app/shell";
export { metadata } from "@/entities/team/routes/team/(dashboard)/profile/page";

export default function Page(props: Omit<ComponentProps<typeof Body>, "claimsPanel">) {
  return <Body {...props} claimsPanel={ProfileClaimsPanel} />;
}

export const dynamic = "force-dynamic";
