// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// The access resolver's facts that only an entity can read (ADR 0013): the roles
// a coaching row or a requisition implies, and the ids a coach's team or a
// person's clients reach. The kernel may import no entity, so the composition
// root registers what the installed entities contribute, at boot, from
// instrumentation.ts. A deployment without an entity has none of its facts.
// The same call hands the kernel this deployment's permission registry, which
// it may not import from app/ itself.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { registerAccessContributions } from "@/kernel/identity/access-contributions";
import { registerPermissionRegistry } from "@/kernel/identity/permission-registry";
import { PERMISSIONS } from "@/app/permissions";
import { accessContributions as coachingAccess } from "@/entities/coaching";
import { accessContributions as teamAccess } from "@/entities/team";

/** Idempotent: registration replaces what was there. */
export function registerAccess(): void {
  registerPermissionRegistry(PERMISSIONS);
  registerAccessContributions([coachingAccess, teamAccess]);
}
