// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// The composition root's event registration. `app/` is the only place that
// knows which entities a deployment installs, so it is the only place that may
// wire publishers to subscribers: an entity that registered itself on import
// would make registration depend on module load order, and a deployment that
// excluded it would still have to import it to find that out.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { resetSubscribers } from "@/kernel/events";
import { subscriptions as boardsSubscriptions } from "@/entities/boards";
import { subscriptions as campaignsSubscriptions } from "@/entities/campaigns";
import { subscriptions as coachingSubscriptions } from "@/entities/coaching";
import { subscriptions as crmSubscriptions } from "@/entities/crm";
import { subscriptions as ideasSubscriptions } from "@/entities/ideas";
import { subscriptions as notificationsSubscriptions } from "@/entities/notifications";
import { subscriptions as onboardingSubscriptions } from "@/entities/onboarding";

let registered = false;

/** Idempotent: Next may evaluate a module more than once per process. */
export function registerEventSubscribers(): void {
  if (registered) return;
  registered = true;
  resetSubscribers();
  boardsSubscriptions();
  campaignsSubscriptions();
  coachingSubscriptions();
  crmSubscriptions();
  ideasSubscriptions();
  notificationsSubscriptions();
  onboardingSubscriptions();
}
