// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// Every surface's navigation, composed from the entities this deployment
// installs. `app/` is the only place that knows which those are, which is why
// the composition happens here and not in the kernel (which may name no entity)
// or in an entity (which would have to name its peers). Each shell owns its
// information architecture and its slots; each entity owns its rows, and a row
// that depends on who is looking carries a `when` capability the shell
// resolves per request.
//
// An installed entity may still leave a pocket out (`internalPaths` in
// entities.manifest.json, which the public fork is staged without). Each
// surface's UNMOUNTED list names the routes this tree lacks, and their rows go
// with them, so the sidebar never links to a page the build does not have.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { composeNav, withoutRoutes, type NavContribution, type NavSection } from "@/kernel/shell/nav";
import { ADMIN_SLOTS } from "@/kernel/shell/admin-ia";
import { TEAM_SLOTS } from "@/kernel/shell/team-ia";
import { PORTAL_SLOTS } from "@/kernel/shell/portal-ia";

import { adminNav as boardsAdminNav } from "@/entities/boards/client";
import { adminNav as campaignsAdminNav } from "@/entities/campaigns/client";
import { adminNav as clientProgramsAdminNav } from "@/entities/client-programs/client";
import { adminNav as companyOsAdminNav } from "@/entities/company-os/client";
import { adminNav as crmAdminNav } from "@/entities/crm/client";
import { adminNav as hiringAdminNav } from "@/entities/hiring/client";
import { adminNav as ideasAdminNav } from "@/entities/ideas/client";
import { adminNav as onboardingAdminNav } from "@/entities/onboarding/client";
import { adminNav as orgAdminNav } from "@/entities/org/client";
import { adminNav as reimbursementsAdminNav } from "@/entities/reimbursements/client";
import { adminNav as retreatsAdminNav } from "@/entities/retreats/client";
import { adminNav as teamAdminNav } from "@/entities/team/client";
import { adminNav as timeOffAdminNav } from "@/entities/time-off/client";

const ADMIN_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...boardsAdminNav,
  ...campaignsAdminNav,
  ...clientProgramsAdminNav,
  ...companyOsAdminNav,
  ...crmAdminNav,
  ...hiringAdminNav,
  ...ideasAdminNav,
  ...onboardingAdminNav,
  ...orgAdminNav,
  ...reimbursementsAdminNav,
  ...retreatsAdminNav,
  ...teamAdminNav,
  ...timeOffAdminNav,
];

const ADMIN_NAV_UNMOUNTED: string[] = [
  "/admin/operations/retreats",
  "/admin/operations/surveys",
  "/admin/revenue/aio-pad",
  "/admin/revenue/companies/[id]/programs",
  "/admin/revenue/marketing",
];

export const ADMIN_NAV: NavSection[] = composeNav(
  ADMIN_SLOTS,
  withoutRoutes(ADMIN_NAV_CONTRIBUTIONS, ADMIN_NAV_UNMOUNTED),
);

import { teamNav as boardsTeamNav } from "@/entities/boards/client";
import { teamNav as campaignsTeamNav } from "@/entities/campaigns/client";
import { teamNav as coachingTeamNav } from "@/entities/coaching/client";
import { teamNav as companyOsTeamNav } from "@/entities/company-os/client";
import { teamNav as crmTeamNav } from "@/entities/crm/client";
import { teamNav as hiringTeamNav } from "@/entities/hiring/client";
import { teamNav as ideasTeamNav } from "@/entities/ideas/client";
import { teamNav as notificationsTeamNav } from "@/entities/notifications/client";
import { teamNav as onboardingTeamNav } from "@/entities/onboarding/client";
import { teamNav as orgTeamNav } from "@/entities/org/client";
import { teamNav as reimbursementsTeamNav } from "@/entities/reimbursements/client";
import { teamNav as retreatsTeamNav } from "@/entities/retreats/client";
import { teamNav as teamTeamNav } from "@/entities/team/client";
import { teamNav as timeOffTeamNav } from "@/entities/time-off/client";

const TEAM_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...boardsTeamNav,
  ...campaignsTeamNav,
  ...coachingTeamNav,
  ...companyOsTeamNav,
  ...crmTeamNav,
  ...hiringTeamNav,
  ...ideasTeamNav,
  ...notificationsTeamNav,
  ...onboardingTeamNav,
  ...orgTeamNav,
  ...reimbursementsTeamNav,
  ...retreatsTeamNav,
  ...teamTeamNav,
  ...timeOffTeamNav,
];

const TEAM_NAV_UNMOUNTED: string[] = [
  "/team/clients/[companyId]/programs",
  "/team/revenue/aio-pad",
  "/team/revenue/companies/[id]/programs",
  "/team/revenue/marketing",
];

export const TEAM_NAV: NavSection[] = composeNav(
  TEAM_SLOTS,
  withoutRoutes(TEAM_NAV_CONTRIBUTIONS, TEAM_NAV_UNMOUNTED),
);

import { portalNav as portalPortalNav } from "@/entities/portal/client";
import { portalNav as timeOffPortalNav } from "@/entities/time-off/client";

const PORTAL_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...portalPortalNav,
  ...timeOffPortalNav,
];

const PORTAL_NAV_UNMOUNTED: string[] = [
  "/portal/programs/[id]",
  "/portal/programs/add",
  "/portal/tokens",
];

export const PORTAL_NAV: NavSection[] = composeNav(
  PORTAL_SLOTS,
  withoutRoutes(PORTAL_NAV_CONTRIBUTIONS, PORTAL_NAV_UNMOUNTED),
);
