// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// Run now on Settings -> Agents (Y.25): the handler of every scheduled routine
// this deployment installs, keyed by its cron path: the GET of its mount, the
// same function Vercel Cron calls. The kernel runs a routine in-process through
// it, never by calling the site's URL, and may import nothing under app/, so
// the composition root registers the handlers at boot, from
// instrumentation.ts. Each loader imports its route only when it is run.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { registerRoutineEntryPoints } from "@/kernel/audit/routine-entry-points";

/** Idempotent: registration replaces what was there. */
export function registerRoutines(): void {
  registerRoutineEntryPoints({
    "/api/cron/account-health/": () => import("@/app/api/cron/account-health/route").then((m) => m.GET),
    "/api/cron/agent-driver/": () => import("@/app/api/cron/agent-driver/route").then((m) => m.GET),
    "/api/cron/automation-watchdog/": () => import("@/app/api/cron/automation-watchdog/route").then((m) => m.GET),
    "/api/cron/blog-publish/": () => import("@/app/api/cron/blog-publish/route").then((m) => m.GET),
    "/api/cron/board-digest/": () => import("@/app/api/cron/board-digest/route").then((m) => m.GET),
    "/api/cron/broadcast-summary/": () => import("@/app/api/cron/broadcast-summary/route").then((m) => m.GET),
    "/api/cron/check-in-reminder/": () => import("@/app/api/cron/check-in-reminder/route").then((m) => m.GET),
    "/api/cron/client-status/": () => import("@/app/api/cron/client-status/route").then((m) => m.GET),
    "/api/cron/client-status-check/": () => import("@/app/api/cron/client-status-check/route").then((m) => m.GET),
    "/api/cron/client-status-driver/": () => import("@/app/api/cron/client-status-driver/route").then((m) => m.GET),
    "/api/cron/coaching-backstops/": () => import("@/app/api/cron/coaching-backstops/route").then((m) => m.GET),
    "/api/cron/coaching-cycle/": () => import("@/app/api/cron/coaching-cycle/route").then((m) => m.GET),
    "/api/cron/coaching-lark-pickup/": () => import("@/app/api/cron/coaching-lark-pickup/route").then((m) => m.GET),
    "/api/cron/coaching-recaps/": () => import("@/app/api/cron/coaching-recaps/route").then((m) => m.GET),
    "/api/cron/contractor-payments/": () => import("@/app/api/cron/contractor-payments/route").then((m) => m.GET),
    "/api/cron/crm-driver/": () => import("@/app/api/cron/crm-driver/route").then((m) => m.GET),
    "/api/cron/daily-check-in/": () => import("@/app/api/cron/daily-check-in/route").then((m) => m.GET),
    "/api/cron/deliverable-sweep/": () => import("@/app/api/cron/deliverable-sweep/route").then((m) => m.GET),
    "/api/cron/email-campaign-send/": () => import("@/app/api/cron/email-campaign-send/route").then((m) => m.GET),
    "/api/cron/email-series-draft/": () => import("@/app/api/cron/email-series-draft/route").then((m) => m.GET),
    "/api/cron/fx-rates/": () => import("@/app/api/cron/fx-rates/route").then((m) => m.GET),
    "/api/cron/hiring-driver/": () => import("@/app/api/cron/hiring-driver/route").then((m) => m.GET),
    "/api/cron/idea-themes/": () => import("@/app/api/cron/idea-themes/route").then((m) => m.GET),
    "/api/cron/ideas-digest/": () => import("@/app/api/cron/ideas-digest/route").then((m) => m.GET),
    "/api/cron/individual-summary/": () => import("@/app/api/cron/individual-summary/route").then((m) => m.GET),
    "/api/cron/inquiry-to-lead/": () => import("@/app/api/cron/inquiry-to-lead/route").then((m) => m.GET),
    "/api/cron/kr-agent-sync/": () => import("@/app/api/cron/kr-agent-sync/route").then((m) => m.GET),
    "/api/cron/letter-weekly/": () => import("@/app/api/cron/letter-weekly/route").then((m) => m.GET),
    "/api/cron/marketing-digest/": () => import("@/app/api/cron/marketing-digest/route").then((m) => m.GET),
    "/api/cron/marketing-recap/": () => import("@/app/api/cron/marketing-recap/route").then((m) => m.GET),
    "/api/cron/marketing-weekly-pulse/": () => import("@/app/api/cron/marketing-weekly-pulse/route").then((m) => m.GET),
    "/api/cron/meeting-cards/": () => import("@/app/api/cron/meeting-cards/route").then((m) => m.GET),
    "/api/cron/monday-nudge/": () => import("@/app/api/cron/monday-nudge/route").then((m) => m.GET),
    "/api/cron/notification-flush/": () => import("@/app/api/cron/notification-flush/route").then((m) => m.GET),
    "/api/cron/onboarding-cycle/": () => import("@/app/api/cron/onboarding-cycle/route").then((m) => m.GET),
    "/api/cron/payment-run/": () => import("@/app/api/cron/payment-run/route").then((m) => m.GET),
    "/api/cron/performance-reviews/": () => import("@/app/api/cron/performance-reviews/route").then((m) => m.GET),
    "/api/cron/proposal-chain/": () => import("@/app/api/cron/proposal-chain/route").then((m) => m.GET),
    "/api/cron/qbo-invoice-sync/": () => import("@/app/api/cron/qbo-invoice-sync/route").then((m) => m.GET),
    "/api/cron/qbo-refresh/": () => import("@/app/api/cron/qbo-refresh/route").then((m) => m.GET),
    "/api/cron/receipt-sweep/": () => import("@/app/api/cron/receipt-sweep/route").then((m) => m.GET),
    "/api/cron/revenue-closed-cards/": () => import("@/app/api/cron/revenue-closed-cards/route").then((m) => m.GET),
    "/api/cron/revenue-content-sync/": () => import("@/app/api/cron/revenue-content-sync/route").then((m) => m.GET),
    "/api/cron/revenue-snapshot/": () => import("@/app/api/cron/revenue-snapshot/route").then((m) => m.GET),
    "/api/cron/routine-reaper/": () => import("@/app/api/cron/routine-reaper/route").then((m) => m.GET),
    "/api/cron/vnd-rates/": () => import("@/app/api/cron/vnd-rates/route").then((m) => m.GET),
    "/api/cron/weekly-sprints/": () => import("@/app/api/cron/weekly-sprints/route").then((m) => m.GET),
    "/api/cron/writer-schedule/": () => import("@/app/api/cron/writer-schedule/route").then((m) => m.GET),
    "/api/cron/zoom-transcripts/": () => import("@/app/api/cron/zoom-transcripts/route").then((m) => m.GET),
  });
}
