"use server";
// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// The global search (S.1). Each installed entity contributes searchers from its
// server door and this file composes the ones this deployment installs, so a
// deployment without an entity simply has no searcher for it, and the kernel's
// palette never names one. Each surface gets its own action. The action guards
// first, inline (ADR 0007), with the permission that enters its surface, then
// hands the guard's answer to every searcher as a SearchActor. runSearch asks a
// contribution only when the person may open the page its hits open, and drops
// any hit whose page they may not open (ADR 0013), so search is never a side
// door; each searcher still scopes its rows the way its own screen does. The
// portal has no action yet: it was left out of v1 on 2026-09-25.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { z } from "zod";
import { requirePermission } from "@/kernel/identity/access-request";
import { requireTeamMember } from "@/kernel/identity/team-auth";
import { runSearch, type SearchContribution, type SearchResult } from "@/kernel/shell/search";
import { searchContributions as boardsSearch } from "@/entities/boards";
import { searchContributions as companyOsSearch } from "@/entities/company-os";
import { searchContributions as crmSearch } from "@/entities/crm";
import { searchContributions as hiringSearch } from "@/entities/hiring";

const CONTRIBUTIONS: SearchContribution[] = [
  ...boardsSearch,
  ...companyOsSearch,
  ...crmSearch,
  ...hiringSearch,
];

// What the browser sends is only ever a typed string; anything else searches for nothing.
const Query = z.string().max(200).catch("");

export async function searchAdmin(query: unknown): Promise<SearchResult> {
  const access = await requirePermission("surface.admin");
  return runSearch(CONTRIBUTIONS, { surface: "admin", admin: access.user, access }, Query.parse(query));
}

export async function searchTeam(query: unknown): Promise<SearchResult> {
  const access = await requirePermission("surface.team");
  // The team searchers scope rows by the team actor (a member's boards), which
  // the permission guard does not carry; everyone holding surface.team has one.
  const team = await requireTeamMember();
  return runSearch(CONTRIBUTIONS, { surface: "team", team, access }, Query.parse(query));
}
