// The CRM: the Revenue section's pipeline, billing and sales calls, on the Admin and Team views alike, and contacts on Admin (ADR 0013). Today requireRevenueAccess opens the Revenue pages to admins and to anyone with the revenue grant, which is the Revenue role.
// Read as text by scripts/gen-deployment.mjs; nothing imports this file. Every
// atom is held by whoever reaches its pages today, so declaring it changes
// nothing until the guard swap.
import type { EntityPermissions } from "@/kernel/identity/permission-declaration";

/** @generator */
export const permissions: EntityPermissions = {
  permissions: {
    "crm.pipeline": "Work the pipeline: leads, inquiries, deals, companies, accounts, clients, affiliates and the revenue outlook",
    "crm.billing": "See billing, across the company and per client",
    "crm.calls": "Review sales calls: meetings and sales intelligence",
    "crm.contacts": "See and edit every contact",
    "crm.agreements": "Prepare and send client agreements for signature",
    // Capabilities that rode on entering the Admin view until AE.1 (ADR 0014):
    // each is its own atom, so a role that opens the Admin view for one job
    // does not carry them.
    "crm.assume": "View a client's portal as one of its members (Assume)",
    "crm.portal-invite": "Invite a team member to the Team view, and revoke or restore their sign-in",
    "crm.collections": "Log a collections chase on an unpaid invoice",
    // Z.10, decision 7: the proposal chain's approval. Not crm.pipeline, which
    // every Revenue member and admin holds: a priced proposal is a commitment,
    // decided by the one person given the Revenue approver role.
    "crm.proposal-approve": "Approve or reject publishing a drafted proposal to the client's portal",
  },
  holders: {
    "crm.pipeline": "admin, revenue",
    "crm.billing": "admin, revenue",
    "crm.calls": "admin, revenue",
    "crm.contacts": "admin",
    "crm.agreements": "super-admin",
    "crm.assume": "admin",
    "crm.portal-invite": "admin",
    "crm.collections": "admin",
    "crm.proposal-approve": "revenue-approver",
  },
  roles: {
    // Seeded with its one atom by 20261009210000_proposal_drafts; who holds it
    // is a grant in Settings -> Access.
    "revenue-approver": {
      "name": "Revenue approver",
      "sentence": "Reads each proposal the proposal chain drafts from a sales call and approves or rejects publishing it to the client's portal.",
      "atoms": "crm.proposal-approve",
    },
  },
  routes: {
    "routes/admin/(dashboard)/contacts/[id]/page": "crm.contacts",
    "routes/admin/(dashboard)/contacts/page": "crm.contacts",
    "routes/admin/(dashboard)/revenue/accounts/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/affiliates/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/billing/clients/page": "crm.billing",
    "routes/admin/(dashboard)/revenue/billing/page": "crm.billing",
    "routes/admin/(dashboard)/revenue/clients/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/companies/[id]/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/companies/[id]/programs/[programId]/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/companies/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/data-health/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/deals/[id]/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/deals/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/demand/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/inquiries/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/leads/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/market/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/meetings/[id]/page": "crm.calls",
    "routes/admin/(dashboard)/revenue/meetings/new/page": "crm.calls",
    "routes/admin/(dashboard)/revenue/meetings/page": "crm.calls",
    "routes/admin/(dashboard)/revenue/outlook/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/pipeline/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/proposals/[id]/page": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/sales-intelligence/[id]/page": "crm.calls",
    "routes/admin/(dashboard)/revenue/sales-intelligence/page": "crm.calls",
    "routes/team/(dashboard)/revenue/accounts/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/affiliates/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/billing/page": "crm.billing",
    "routes/team/(dashboard)/revenue/clients/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/companies/[id]/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/companies/[id]/programs/[programId]/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/companies/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/data-health/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/deals/[id]/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/deals/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/demand/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/inquiries/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/leads/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/market/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/meetings/[id]/page": "crm.calls",
    "routes/team/(dashboard)/revenue/meetings/new/page": "crm.calls",
    "routes/team/(dashboard)/revenue/meetings/page": "crm.calls",
    "routes/team/(dashboard)/revenue/outlook/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/pipeline/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/proposals/[id]/page": "crm.pipeline",
    "routes/team/(dashboard)/revenue/sales-intelligence/[id]/page": "crm.calls",
    "routes/team/(dashboard)/revenue/sales-intelligence/page": "crm.calls",
  },
  actions: {
    "lib/affiliates-actions": "crm.pipeline",
    "lib/assume-actions": "crm.assume",
    "lib/companies-actions": "crm.pipeline",
    "lib/company-documents-actions": "crm.pipeline",
    "lib/contacts-actions": "crm.contacts",
    "lib/delivered-addition-actions": "crm.pipeline",
    "lib/hours-actions": "crm.pipeline",
    "lib/inquiry-triage-actions": "crm.pipeline",
    "lib/lark-meeting-actions": "crm.calls",
    "lib/meetings-actions": "crm.calls",
    "lib/meeting-followup-actions": "crm.calls",
    "lib/person-tags-actions": "crm.contacts",
    "lib/portal-member-actions": "crm.pipeline",
    "lib/program-actions": "crm.pipeline",
    "lib/proposal-actions": "crm.pipeline",
    "lib/proposal-decide-actions": "crm.proposal-approve",
    "lib/proposal-run-actions": "crm.calls",
    "lib/renewal-actions": "crm.pipeline",
    "lib/team-portal-actions": "crm.portal-invite",
    "lib/token-allocation-actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/billing/collections-actions": "crm.collections",
    "routes/admin/(dashboard)/revenue/deals/actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/deals/agreement-actions": "crm.agreements",
    "routes/admin/(dashboard)/revenue/deals/attribution-actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/deals/bulk-actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/inquiries/actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/leads/actions": "crm.pipeline",
    "routes/admin/(dashboard)/revenue/targets-actions": "crm.pipeline",
  },
  implies: {},
};
