// The Supabase tables the crm entity owns (design §4).
export const CRM_TABLES = [
  "account_health_snapshots",
  "call_scorecards",
  "call_transcripts",
  "deal_stage_current",
  "deal_stage_log",
  "deals",
  "inquiries",
  "inquiry_triage",
  "lead",
  "lifecycle_transitions",
  "meeting_action_items",
  "meeting_associations",
  "meeting_followups",
  "meeting_participants",
  "meetings",
  "pipeline_stages",
  "pipelines",
  "proposal_drafts",
  "renewals",
  "revenue_snapshots",
  "revenue_targets",
] as const;
