// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/boards/routes/team/(dashboard)/my-week/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import type { ComponentProps } from "react";
import Body from "@/entities/boards/routes/team/(dashboard)/my-week/page";
import { InboxLine } from "@/app/shell";
export { metadata } from "@/entities/boards/routes/team/(dashboard)/my-week/page";

export default function Page(props: Omit<ComponentProps<typeof Body>, "inboxLine">) {
  return <Body {...props} inboxLine={InboxLine} />;
}

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";
