// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/team/routes/team/(dashboard)/kudos/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import "@/app/styles/team-home.css";
export { default } from "@/entities/team/routes/team/(dashboard)/kudos/page";

export const dynamic = "force-dynamic";
